export const LOCAL_SEND_MESSAGE = "LOCAL_SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const USER_CONNECTED = "USER_CONNECTED";
export const USERS_LIST = "USERS_LIST";
export const SELF_CONNECT = "SELF_CONNECT";
export const USER_DISCONNECTED = "USER_DISCONNECTED";
